//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plant_Paradise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public int Comment_id { get; set; }
        [DisplayName("Comment Body")]
        public string Comment_text { get; set; }
        [DisplayName("User Name")]
        public string userId { get; set; }

        [DisplayName("product Name")]
        public Nullable<int> Product_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Product Product { get; set; }
    }
}
