//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plant_Paradise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        public int Feedback_id { get; set; }
        [DisplayName("Feeback Body")]
        public string Feedback_text { get; set; }
        [DisplayName("Feeback date")]
        public Nullable<System.DateTime> Feedback_Date { get; set; }
        public string userId { get; set; }
        [DisplayName("Status")]
        public Nullable<int> IsAccepted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
