//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plant_Paradise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Transaction
    {
        public int TransactionId { get; set; }
        [DisplayName("Total Price")]
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        [DisplayName("Order ID")]
        public string Order_id { get; set; }
        [DisplayName("User Name")]
        public string userId { get; set; }
        [DisplayName("Phone Number")]
        public string Phone_Contact { get; set; }
        [DisplayName("User Address")]
        public string User_Location { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Order Order { get; set; }
    }
}
